import type { Metadata } from "next";
import { getServerSession } from "next-auth/next";

import Body from "./components/Body";
import { authOptions } from "./api/auth/[...nextauth]/route";

export const metadata: Metadata = {
  title: "CSS Challenges",
  description: "Generated by create next app",
};

export default async function Home() {
  const session = await getServerSession(authOptions);

  let tasksData;

  if (session) {
    const response = await fetch(`${process.env.BACKEND_URL}/api/tasks-users/`, {
      headers: {
        Authorization: `Bearer ${session.accessToken}`,
      },
      next: { tags: ["userTasks"] },
    });

    tasksData = await response.json();
  }

  const topicsResponse = await fetch(`${process.env.BACKEND_URL}/api/topics/`);
  const topics = await topicsResponse.json();

  // TODO - handle the error cases where the backend is not working
  // TODO - why the fuck is it a deceptive site - fix it
  // TODO - handle adding snippets into the add task form
  return (
    <>
      <Body topics={topics} />
    </>
  );
}
