import { getServerSession } from "next-auth/next";
import type { Metadata } from "next";

import Title from "./components/Title";
import { Suspense } from "react";
import { LoadingMainPage } from "./components/Loadings/Index";
import { authOptions } from "./api/auth/[...nextauth]/route";
import Body from "./components/Body";

export const metadata: Metadata = {
  title: "CSS Challenges",
  description: "Generated by create next app",
  other: {
    "google-site-verification": process.env.GOOGLE_SITE_VERIFICATION!,
  },
};

// Why use Suspense instead of Next.js loading.tsx?
// loading.tsx is loaded for all children, so even a few routes deep the loading screen is shown from the route many routes above
// TODO - Flash of unstyled content (FOUC) - fix it
export default function Home() {
  return (
    <>
      <Title />
      <Suspense fallback={<LoadingMainPage />}>
        <Main />
      </Suspense>
    </>
  );
}

async function Main() {
  const session = await getServerSession(authOptions);

  let tasksData;

  if (session) {
    const response = await fetch(`${process.env.BACKEND_URL}/api/tasks-users/`, {
      headers: {
        Authorization: `Bearer ${session.accessToken}`,
      },
      next: { tags: ["userTasks"] },
    });

    tasksData = await response.json();
  }

  const topicsResponse = await fetch(`${process.env.BACKEND_URL}/api/topics/`, { next: { tags: ["topics"] } });
  const topics = await topicsResponse.json();

  return <Body topics={topics} />;
}
